// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xayhixgsgqzakrvskwza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhheWhpeGdzZ3F6YWtydnNrd3phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MjAwNTgsImV4cCI6MjA2OTI5NjA1OH0.X6xWh1pJPqmcZkk1oDp3AZ0QixJHZF8GZCTsh7RUOqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});